DROP TABLE IF EXISTS `users_staff`;
CREATE TABLE IF NOT EXISTS `users_staff` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(50) NOT NULL ,
  `mail` varchar(50) NOT NULL ,
  `login` varchar(50) NOT NULL ,
  `password` varchar(255) NOT NULL ,
  `name` varchar (25) NOT NULL ,
  `familyName` varchar (50) NOT NULL ,
  `phone_number` varchar(10) NOT NULL ,
  `rank` enum('Prescripteur', 'Valideur', 'Membre Commission', 'Président Comission', 'Administrateur') NOT NULL ,
  `regsitration_IP` varchar (30) NOT NULL ,
  `last_IP` varchar (30) DEFAULT NULL ,
  `join_date` bigint(20) DEFAULT NULL,
  `structure_name` varchar (50) NOT NULL ,
  `structure_code` varchar (50) NOT NULL ,
  `structure_department` varchar (50) DEFAULT NULL ,
  `last_update_password` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8_general_ci;

DROP TABLE IF EXISTS `users_youth`;
CREATE TABLE IF NOT EXISTS `users_youth` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `youth_id` varchar(50) NOT NULL ,
  `civility` enum('Mme', 'Mr', 'None') DEFAULT 'None',
  `name` varchar (25) NOT NULL ,
  `familyName` varchar (50) NOT NULL ,
  `address` TINYTEXT NOT NULL ,
  `postal_code` int(6) ,
  `town` varchar(50) ,
  `phone_number` BIGINT(10) NOT NULL ,
  `fixe_number` BIGINT(10) NOT NULL ,
  `mail` VARCHAR(50) NOT NULL ,
  `birthdate` BIGINT(21) NOT NULL ,
  `birthplace_town` varchar(50) DEFAULT NULL ,
  `birthplace_postal_code` int(6) DEFAULT NULL ,
  `birthplace_postal_country` varchar(50) DEFAULT NULL ,
  `nationality` varchar (4) NOT NULL ,
  `arrived_in_france` BIGINT(21) NOT NULL,
  `residence_permit` varchar(20) DEFAULT NULL,
  `end_residence_permit` bigint(21) DEFAULT NULL,
  `allow_to_work` ENUM('Y', 'N') DEFAULT NULL,
  `QPV` ENUM('Y', 'N') DEFAULT NULL,
  `ZRR` ENUM('Y', 'N') DEFAULT NULL,
  `ZSP` ENUM('Y', 'N') DEFAULT NULL,
  `ZUS` ENUM('Y', 'N') DEFAULT NULL,
  `RQTH` ENUM('Y', 'N') DEFAULT NULL,
  `id_card` varchar(75) DEFAULT NULL ,
  `social_s_number` VARCHAR(20) NOT NULL ,
  `pole_e_number` VARCHAR(15) DEFAULT NULL ,
  `life_situation` ENUM('Cohabitant', 'Dé-cohabitant', 'Célibataire', 'Vie en couple') ,
  `annual_taxable_income` int(6) ,
  `parts_number` ?? ,
  `dependent_children` int(2) ,
  `fiscal_attachment` ENUM('Y', 'N') ,
  `lodging` ENUM('Locataire', 'Propriétaire', 'Sans hébargement', 'Chez les parents', 'Chez la famille', 'Chez les amis', 'En foyer', 'Au CHRS', 'None') ,
  `other_lodging` VARCHAR(50),
  `was_registred_in_ML` ENUM('Y', 'N'),
  `attachment_antenna` VARCHAR (50) DEFAULT NULL,
  `GJ_referring_in_charge` VARCHAR(50),
  `phone_GJ_referring_in_charge` VARCHAR(10) DEFAULT NULL,
  `staff_in_charge` VARCHAR(50),
  `phone_staff_in_charge` VARCHAR(10) DEFAULT NULL,
  `partner` VARCHAR(50) DEFAULT NULL ,
  `phone_partner` varchar(10) DEFAULT NULL ,
  `GJ_accompaniment` varchar(50) DEFAULT 'Aucun',
  `student_training` ENUM('Y', 'N'),
  `youth_education` ENUM('Y', 'N'),
  `youth_employment` ENUM('Y', 'N'),
  `younth_educated` ENUM('Y', 'N'),
  `last_classroom`  VARCHAR(50) DEFAULT NULL,
  `last_classroom_date`  BIGINT(21) DEFAULT NULL,
  `greatest_qualification`  VARCHAR(50) DEFAULT NULL,
  `institution`  VARCHAR(50) DEFAULT NULL,

)ENGINE=InnoDB DEFAULT CHARSET=utf8_general_ci;